#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
MYIP=$(wget -qO- ifconfig.me/ip);
echo "Checking VPS"
clear
echo -e ""
echo -e "\e[1;32m═════════════════════════════════════════" | lolcat
echo -e "          \e[1;31m\e[1;31m═[\e[mBENGKEL\e[1;31m]═\e[m" 
echo -e "\e[1;32m═════════════════════════════════════════" | lolcat
echo -e " 1\e[1;33m)\e[m  setting"
echo -e " 2\e[1;33m)\e[m  base-port"
echo -e " 3\e[1;33m)\e[m  base-port-WC"
echo -e " 4\e[1;33m)\e[m  base-script"
echo -e " 5\e[1;33m)\e[m  bench-network"
echo -e " 6\e[1;33m)\e[m  clearcache"
echo -e " 7\e[1;33m)\e[m  connections"
echo -e " 8\e[1;33m)\e[m  create"
echo -e " 9\e[1;33m)\e[m  create_random"
echo -e " 10\e[1;33m)\e[m  create_trial"
echo -e " 11\e[1;33m)\e[m  delete_expired"
echo -e " 12\e[1;33m)\e[m  diagnose"
echo -e " 13\e[1;33m)\e[m  edit_openssh"
echo -e " 14\e[1;33m)\e[m  edit_openvpn"
echo -e " 15\e[1;33m)\e[m  edit_ports"
echo -e " 16\e[1;33m)\e[m  edit_squid3"
echo -e " 17\e[1;33m)\e[m  edit_stunnel4"
echo -e " 18\e[1;33m)\e[m  locket_list"
echo -e " 19\e[1;33m)\e[m  menu"
echo -e " 20\e[1;33m)\e[m  options"
echo -e " 21\e[1;33m)\e[m  ram"
echo -e " 22\e[1;33m)\e[m  reboot_sys"
echo -e " 23\e[1;33m)\e[m  reboot_sys_auto"
echo -e " 24\e[1;33m)\e[m  restart_services"
echo -e " 25\e[1;33m)\e[m  server"
echo -e " 26\e[1;33m)\e[m  set_multilogin_autokill"
echo -e " 27\e[1;33m)\e[m  set_multilogin_autokill_lib"
echo -e " 28\e[1;33m)\e[m  show_ports"
echo -e " 29\e[1;33m)\e[m  user_delete"
echo -e " 30\e[1;33m)\e[m  user_details"
echo -e " 31\e[1;33m)\e[m  user_details_lib"
echo -e " 32\e[1;33m)\e[m  user_extend"
echo -e " 33\e[1;33m)\e[m  user_list"
echo -e " 34\e[1;33m)\e[m  user_lock"
echo -e " 35\e[1;33m)\e[m  user_unlock"
echo -e ""
echo -e "\e[1;32m══════════════════════════════════════════" | lolcat
echo -e " x)   MENU"
echo -e "\e[1;32m══════════════════════════════════════════" | lolcat
echo -e ""
read -p "     Please Input Number  [1-35 or x] :  "  setting
echo -e ""
case $setting in
1)
accounts
;;
2)
base-port
;;
3)
base-port-WC
;;
4)
base-script
;;
5)
bench-network
;;
6)
clearcache
;;
7)
connections
;;
8)
create
;;
9)
create_random
;;
10)
create_trial
;;
11)
delete_expired
;;
12)
diagnose
;;
13)
edit_openssh
;;
14)
edit_openvpn
;;
15)
edit_ports
;;
16)
edit_squid3
;;
17)
edit_stunnel4
;;
18)
locket_list
;;
19)
menuu
;;
20)
options
;;
21)
ram
;;
22)
reboot_sys
;;
23)
reboot_sys_auto
;;
24)
restart_services
;;
25)
server
;;
26)
set_multilogin_autokill
;;
27)
set_multilogin_autokill_lib
;;
28)
show_ports
;;
29)
user_delete
;;
30)
user_details
;;
31)
user_details_lib
;;
32)
user_extend
;;
33)
user_list
;;
34)
user_lock
;;
35)
user_unlock
;;
x)
exit
;;
*)
echo "Please enter an correct number"
;;
esac